"""v1_add_column_day

Revision ID: a42bb23752b2
Revises: d8126ddb0cfe
Create Date: 2025-06-02 11:33:58.131677

"""
from typing import Sequence, Union
from datetime import date

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42bb23752b2'
down_revision: Union[str, None] = 'd8126ddb0cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('day', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.delete_column('tracker', 'day')
    # ### end Alembic commands ###
